#ifndef _PARTMGRP_
#define _PARTMGRP_

//
// Internal I/O Control Codes for communication with the Partition Manager
//
#define IOCTL_PARTMGR_BASE          ((ULONG) 'p')

#define IOCTL_INTERNAL_PARTMGR_CHECK_FOR_UNCLAIMED_PARTITIONS \
    CTL_CODE(IOCTL_PARTMGR_BASE, 0, METHOD_BUFFERED,  FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_INTERNAL_PARTMGR_EJECT_VOLUME_MANAGERS \
    CTL_CODE(IOCTL_PARTMGR_BASE, 1, METHOD_BUFFERED,  FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_INTERNAL_PARTMGR_QUERY_DISK_SIGNATURE \
    CTL_CODE(IOCTL_PARTMGR_BASE, 2, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_INTERNAL_PARTMGR_SIGNATURE_CHECK \
    CTL_CODE(IOCTL_PARTMGR_BASE, 3, METHOD_BUFFERED, FILE_READ_ACCESS)

//
// Input structure for IOCTL_INTERNAL_PARTMGR_QUERY_DISK_SIGNATURE
//
typedef struct _PARTMGR_SIGNATURE_INFORMATION
{
    ULONG MbrSignature;
    ULONG GptSignature;
} PARTMGR_SIGNATURE_INFORMATION, *PPARTMGR_SIGNATURE_INFORMATION;

#endif
